apiVersion: apps/v1
kind: Deployment
metadata:
  name: kisaanai-frontend
  labels:
    app: kisaanai-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kisaanai-frontend
  template:
    metadata:
      labels:
        app: kisaanai-frontend
    spec:
      containers:
      - name: frontend
        image: docker.io/nuctan/kisaanai-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: kisaanai-frontend-service
spec:
  type: LoadBalancer
  selector:
    app: kisaanai-frontend
  ports:
  - port: 80
    targetPort: 80
